# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kachen <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/06/02 23:15:50 by kachen            #+#    #+#              #
#    Updated: 2018/06/02 23:15:51 by kachen           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2
SRCS = cmp.c ft_putchar.c ft_putnbr.c ft_putstr.c main.c r0.c r1.c r2.c r3.c r4.c

all:
	gcc $(SRCS) -o $(NAME) -g

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all
